name: zakir
description: Mobile Dhikr Application

version: 1.0.1+4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 0.1.3
  provider: 4.3.2+1
  audioplayers: 0.15.1
  path_provider: 1.6.11
  http: 0.12.2
  sliding_up_panel: 1.0.2
  google_fonts: 1.1.0
  shared_preferences: 0.5.8
  flutter_local_notifications: 1.4.4+4
  connectivity: 0.4.9+2
  get_it: 4.0.4
  url_launcher: 5.5.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/zakir-logo-big-green.png"

dev_dependencies:

  flutter_launcher_icons: 0.7.5
  rect_getter: 0.1.0

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:  
    - assets/
    - assets/data/
    - assets/icons/    
    - assets/images/    

  fonts:
    - family: Traditional-Arabic
      fonts:
        - asset: fonts/Traditional-Arabic.ttf

    - family: Amiri-Quran
      fonts:
        - asset: fonts/Amiri-Quran.ttf


